### ISSUE TITLE
Unable to add devices

### ISSUE THREAD

**Issue by Cochrane-Server** [seriousm4x/UpSnap#17]
I'm having an issue after updating to the latest upsnap where all 3 of the computers I had added are missing. I've tried restoring from json backedup file, deleted the docker containers and creating from new and still can't add.

version: "3"
services:
  app:
    container_name: upsnap_app
    image: seriousm4x/upsnap:latest
    network_mode: host
    restart: unless-stopped
    environment:
      - FRONTEND_PORT=8100
      - BACKEND_PORT=8001
      - DB_TYPE=sqlite # required
      - REDIS_HOST=127.0.0.1 # required (make sure to use the same ip as below)
      - REDIS_PORT=6379 # required (make sure to use the same port as below)
      #- PING_INTERVAL=5 # optional (default: 5 seconds)
      #- DJANGO_SUPERUSER_USER=admin # optional (default: backend login disabled)
      #- DJANGO_SUPERUSER_PASSWORD=admin # optional (default: backend login disabled)
      #- DJANGO_SECRET_KEY=secret # optional (default: randomly generated)
      #- DJANGO_DEBUG=True # optional (default: False)
      #- DJANGO_LANGUAGE_CODE=de # optional (default: en)
      #- DJANGO_TIME_ZONE=Europe/Berlin # optional (default: UTC)
    depends_on:
      redis:
        condition: service_healthy
  redis:
    container_name: upsnap_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 10s

**Comment by seriousm4x** [comment]
Have you checked the docker logs? Is there any error?

**Comment by craigcochrane** [comment]
So I am now trying this is a separate VM (Arch as well, but don't think it matters and am getting the same issue. I setup the docker-compose container, setup the network scanning range and go to add the PC to devices but it fails.

The docker log for upsnap_app shows:

[2022-04-30 10:47:19 +0000] [23] [INFO] ('192.168.1.5', 51653) - "WebSocket /wol/" [accepted]
[2022-04-30 10:47:19 +0000] [23] [INFO] connection open
  [10:47:19] 200 ─ 1.21ms ─ /build/webfonts/fa-solid-900.woff2
[2022-04-30 10:48:00 +0000] [23] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 184, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/opt/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/opt/venv/lib/python3.9/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/opt/venv/lib/python3.9/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/opt/venv/lib/python3.9/site-packages/channels/generic/websocket.py", line 194, in websocket_receive
    await self.receive(text_data=message["text"])
  File "/app/backend/wol/consumers.py", line 87, in receive
    await self.update_device(received["data"])
  File "/opt/venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.9/site-packages/channels/db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/asgiref/sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "/app/backend/wol/consumers.py", line 190, in update_device
    "link": data["link"],
KeyError: 'link'

I'm using the sqlite version of the docker-compose image but I may try another as well.

**Comment by Cochrane-Server** [comment]
Same error in mysql version

**Comment by seriousm4x** [comment]
Ah yes, I'll fix it shortly

**Comment by Cochrane-Server** [comment]
Wow thanks that was quick. If i do docker-compose down, docker-compose pull, docker-compose up -d should it now be resolved or do I need to wait for update? Reason I ask is it still happens.

[2022-04-30 19:10:15 +0000] [28] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 184, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/opt/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/opt/venv/lib/python3.9/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/opt/venv/lib/python3.9/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/opt/venv/lib/python3.9/site-packages/channels/generic/websocket.py", line 194, in websocket_receive
    await self.receive(text_data=message["text"])
  File "/app/backend/wol/consumers.py", line 87, in receive
    await self.update_device(received["data"])
  File "/opt/venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.9/site-packages/channels/db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/asgiref/sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "/app/backend/wol/consumers.py", line 190, in update_device
    "link": data["link"],
KeyError: 'link'
[2022-04-30 19:10:15 +0000] [28] [INFO] connection closed


Thanks again

**Comment by seriousm4x** [comment]
Hm... I tested it here on my pc and it worked after my fix. I'll look into it again

**Comment by seriousm4x** [comment]
So I ran version 1.4.1 and exported a json, then spin up 2.0.5 and imported the json there without errors.
maybe do `docker-compose down && docker system prune -af && docker-compose up -d` and see if that helps. This will delete all images which are not in use.

**Comment by Cochrane-Server** [comment]
Originally was running this on a Proxmox Arch VM, although not sure it matters.
Tried in Hyper-V Debian and there is an issue with the version/yaml structure...not relevant just trying to rule things out.

Trying now in fresh Hyper-V Arch VM and am getting the same issue that I cannot add any devices. This time I'm trying to add a different device.

Appreciate your efforts - this is a nice tool to have.

--

[2022-05-02 19:40:39 +0000] [23] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 184, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/opt/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/opt/venv/lib/python3.9/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/opt/venv/lib/python3.9/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/opt/venv/lib/python3.9/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/opt/venv/lib/python3.9/site-packages/channels/generic/websocket.py", line 194, in websocket_receive
    await self.receive(text_data=message["text"])
  File "/app/backend/wol/consumers.py", line 87, in receive
    await self.update_device(received["data"])
  File "/opt/venv/lib/python3.9/site-packages/asgiref/sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.9/site-packages/channels/db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/asgiref/sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "/app/backend/wol/consumers.py", line 190, in update_device
    "link": data["link"],
KeyError: 'link'
[2022-05-02 19:40:39 +0000] [23] [INFO] connection closed


![2022-05-02 16_40_14-UpSnap and 11 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/55543624/166314246-a96e9df4-ab3f-4e3f-b7e0-ea290a1d5d2b.png)

**Comment by seriousm4x** [comment]
I think this is already fixed in https://github.com/seriousm4x/UpSnap/commit/42bb71a017e08e76fd252572881d8d1ce1c57f0b but didn't make it into the release yet. Guess I'll push 2.0.6 then

**Comment by seriousm4x** [comment]
https://github.com/seriousm4x/UpSnap/releases/tag/v2.0.6
Please test again

**Comment by Cochrane-Server** [comment]
Fixed! thank you so much.
